# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-09-28 11:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20180928_1800'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('o_num', models.CharField(max_length=128)),
                ('o_time', models.DateTimeField(auto_now=True)),
                ('o_status', models.IntegerField(default=0)),
                ('o_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.UserModel')),
            ],
            options={
                'db_table': 'axf_order',
            },
        ),
        migrations.CreateModel(
            name='OrderAndGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('og_count', models.IntegerField(default=1)),
                ('og_num', models.CharField(max_length=128)),
                ('og_goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Goods')),
            ],
            options={
                'db_table': 'axf_order_goods',
            },
        ),
    ]
